import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildStage2Report, validateStage2Report, attemptBindingHash, type Stage2AttemptReport } from '../src/stage-2-report.ts';
import { canonicalize, deriveCommitments, identityCommitment, type RawStage2Observation } from '../src/stage-2-isolation.ts';

function raw(id: string, status: 'passed' | 'failed' = 'passed'): RawStage2Observation { const workspace=`/private/${id}`; const result=`result-${id}`; const commit=status==='passed'?id.repeat(40).slice(0,40):null; const failure=status==='passed'?null:'INJECTED_WORKER_FAILURE'; const checks=[{name:'ok',passed:status==='passed'}]; const context={node_id:`node-${id}`,attempt_id:`attempt-${id}`,workspace_path:workspace,pi_session_dir:`/session/${id}`,pi_runtime_parent:`/runtime/${id}`,attempt_nonce:`nonce-${id}`,result_destination:{kind:'sqlite',id:result}}; return {attemptId:`attempt-${id}`,nodeId:`node-${id}`,verifier:{status,commitSha:commit,failureCode:failure,checks},persisted:{resultId:result,status,commitSha:commit,failureCode:failure,checks},workspace,piSession:`/session/${id}`,nonce:`nonce-${id}`,resultId:result,repositoryInstance:workspace,privateRuntime:`/runtime/${id}`,broker:`/broker/${id}`,inventory:{workspace,privateRuntime:`/runtime/${id}`,session:`/session/${id}`,broker:`/broker/${id}`,resultId:result},executionContext:context,actorIdentity:{actor:'pool-worker',authority:'single-attempt-execution',node_id:`node-${id}`,attempt_id:`attempt-${id}`,target_repo:'fixture',target_branch:'main',context_source:'launcher-verified',can_modify_pool_policy:false},attemptContract:{node_id:`node-${id}`,attempt_id:`attempt-${id}`,target_repo:'fixture',target_branch:'main'},resourceAttemptId:`attempt-${id}`,expected:{workspace,targetRepo:'fixture',targetBranch:'main',nodeId:`node-${id}`,attemptId:`attempt-${id}`}}; }
function attempt(id:string,status:'passed'|'failed'='passed',slot=0):Stage2AttemptReport {const r=raw(id,status);const commitments=deriveCommitments(r);const a={attempt_id:r.attemptId,node_id:r.nodeId,slot_index:slot,status,builder_model:'moonshot/kimi-k2.7-code',commit_sha:r.verifier.commitSha,failure_code:r.verifier.failureCode,verifier_checks:[{name:'ok',passed:status==='passed'}],isolation:{...commitments,attempt_binding_hash:''}} as Stage2AttemptReport;return {...a,isolation:{...a.isolation,attempt_binding_hash:attemptBindingHash(a)}};}
function report(){return buildStage2Report({stage1Provenance:{report_path:'reports/stage-1-proof-report.json',report_sha256:'0'.repeat(64),model:'moonshot/kimi-k2.7-code',base_commit:'a'.repeat(40),result_commit:'b'.repeat(40)},attempts:[attempt('a','passed',0),attempt('b','failed',1),attempt('c','passed',0)],timingPoints:[],cleanupDisposition:{workspaceRemoved:true,sessionRemoved:true},startedAt:new Date(),finishedAt:new Date()});}
describe('Stage 2 isolation commitments',()=>{
 it('uses strict canonical unsalted domain-separated commitments',()=>{assert.equal(canonicalize({b:1,a:['x']}),canonicalize({a:['x'],b:1}));assert.equal(identityCommitment('workspace','same'),identityCommitment('workspace','same'));assert.notEqual(identityCommitment('workspace','same'),identityCommitment('broker','same'));assert.throws(()=>canonicalize(Number.NaN));assert.throws(()=>canonicalize(undefined));});
 it('accepts bounded report, excludes the comprehensive prohibited raw corpus, detects each corpus value in a contaminated report, and rejects binding mutation',()=>{const r=report();assert.equal(validateStage2Report(r).ok,true);const serialized=JSON.stringify(r);const fixtureRawValues=['a','b','c'].flatMap(id=>{const observation=raw(id);return [observation.piSession,observation.privateRuntime,observation.broker];});const prohibited=['/private/','/Users/example/secret','/var/folders/private','/session/a','/runtime/a','/broker/a',...fixtureRawValues,'nonce-a','result-a','Stage 2 fixture job','Apply the deterministic fixture change','Fixture tests fail at the base commit','Attempt contract:','worker prompt','PI_PROCESS_OUTPUT_MUST_NOT_BE_RETAINED','transcript','MOONSHOT_API_KEY','sk-private-credential-value','password=super-secret'];const assertNoProhibitedRawValue=(candidate:string)=>{for(const value of prohibited)assert.equal(candidate.includes(value),false,`retained report leaked ${value}`);};assertNoProhibitedRawValue(serialized);for(const value of prohibited)assert.throws(()=>assertNoProhibitedRawValue(`${serialized}${value}`),/retained report leaked/);const changed={...r,attempts:[{...r.attempts[0]!,isolation:{...r.attempts[0]!.isolation,workspace_commitment:'f'.repeat(64)}},r.attempts[1]!,r.attempts[2]! ]};assert.equal(validateStage2Report(changed).ok,false);});
 it('rejects commitment duplication as defense in depth',()=>{const r=report();const a=r.attempts[0]!,b=r.attempts[1]!;const bad={...r,attempts:[a,{...b,isolation:{...b.isolation,nonce_commitment:a.isolation.nonce_commitment,attempt_binding_hash:attemptBindingHash({...b,isolation:{...b.isolation,nonce_commitment:a.isolation.nonce_commitment}})}},r.attempts[2]!]};assert.equal(validateStage2Report(bad).ok,false);});
});
